### ISSUE TITLE
Bump react v to 16.x.x

### ISSUE THREAD

**Issue by ahmadalibaloch** [bvaughn/react-virtualized-select#104] opened 2018-02-12 15:00 UTC
Update react to latest version please.

**Comment by bvaughn** [comment] 2018-02-12 15:36
Install whatever version of `react` you want _in your project_. This package specifies [any version greater than 15.3.0 _or_ 16.0.0-alpha](https://github.com/bvaughn/react-virtualized-select/blob/master/package.json#L124).

Duplicate of #92, #99

**Closed by bvaughn** 2018-02-12 15:36 UTC

**Comment by ahmadalibaloch** [comment] 2018-02-13 07:48
I just updated my project to react 16, but  webpack keeps showing unmet peer dependency for this library citing react 15.x :-1:

**Comment by bvaughn** [comment] 2018-02-13 15:32
I don't know why it would do that, as the peer dependencies definitely include React 16:
![screen shot 2018-02-13 at 7 31 07 am](https://user-images.githubusercontent.com/29597/36157944-e643ba28-108f-11e8-99cb-8222c3c0c41e.png)

Test it out yourself by typing "react" and "^15.3.0 || ^16.0.0-alpha" into [an online semver checker](https://semver.npmjs.com/).

![screen shot 2018-02-13 at 7 32 09 am](https://user-images.githubusercontent.com/29597/36157996-0ebf313a-1090-11e8-8dcc-771591a2bfda.png)

You can file a bug against Webpack if you're convinced it's a problem with Webpack.
