### ISSUE TITLE
Not compatible with react-virtualized@9.10.1

### ISSUE THREAD

**Issue by seanpavlov** [bvaughn/react-virtualized-select#76] opened 2017-09-20 08:47 UTC
I was trying react-virtualized-select, but didn't get it to work at first.
Here are the versions of the packages I used at first:
**react-select**@1.0.0-rc.10
**react-virtualized-select**@3.1.0
**react-virtualized**@9.10.1

The result is the following:
**Safari**
![ezgif-3-04b7da2403-2](https://user-images.githubusercontent.com/1535966/30634354-1e1cbb02-9def-11e7-9a9b-dffdece86629.gif)

**Chrome**
![ezgif-3-baa537d0a8](https://user-images.githubusercontent.com/1535966/30634680-2cd2adc2-9df0-11e7-835b-b0f823280ba0.gif)

The solution for me was to downgrade the version of **react-virtualized** to **9.0.0** in order to make it scroll smoothly. 

Otherwise it's great and really makes react-select scroll smoothly, so thanks! :-)

**Update 1:** Ok, now I've found out that it wasn't only because I changed the version of react-virtualized that it worked. It wasn't until I also copied VirtualizedSelect.js from your repo to my project that it started to behave as normal.

**Comment by bvaughn** [comment] 2017-09-20 15:06
Closing as a duplicate of #75. Let's talk there.

**Closed by bvaughn** 2017-09-20 15:06 UTC
