### ISSUE TITLE
Problem with IE11

### ISSUE THREAD

**Issue by konstantingassmann** [bvaughn/react-virtualized-select#51] opened 2017-03-29 11:36 UTC
Hi,
I've encountered a problems with the component in IE11.
When updating another field of my form, i get multiple errors in the Console which says:
`"Unable to get property 'getHostNode' of undefined or null reference"`

![ie11-problem](https://cloud.githubusercontent.com/assets/5058316/24452552/1d6bc468-1484-11e7-851c-d4a0330f9e56.png)

If it helps, here are the versions of the things i'm running:
IE11 running on Win8.1
React v15.4.2
react-virtualized-select v2.4.0
redux v5.0.3

A fix for this would be great.
Thanks

**Comment by bvaughn** [comment] 2017-03-29 14:38
> When updating another field of my form, i get multiple errors in the Console

If the errors happen after you update another field, what makes you assume they're caused by react-virtualized-select?

Without any more information than is provided here in this issue, I really can't help. 😄

**Comment by bvaughn** [comment] 2017-03-29 14:40
Neither react-virtualized-select nor the libraries it sits on top of (react-select and react-virtualized) have any references to `getHostNode`. I assume this is actually an issue elsewhere in your app.

Going to close it for now. We can keep talking though. If you have more info that makes it seem likely this is an RVS bug I'll reopen! 😄

**Closed by bvaughn** 2017-03-29 14:40 UTC

**Comment by konstantingassmann** [comment] 2017-03-29 14:48
I assumed it's a problem with react-virtualized-select because after removing the component from the form everything worked as expected.

Turns out that it was a problem with filterOptions callback, where a polyfill was missing.

Thanks! and sorry for the trouble 😄
